//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupSpirit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Game_Player_Progress
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Version { get; set; }
        public int SS_PlayerId { get; set; }
    
        public virtual SS_Player SS_Player_Id { get; set; }
        public virtual SS_Game_Component SS_Game_Component_Name_Id { get; set; }
    }
}
