//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupSpirit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_University_Faculty
    {
        public SS_University_Faculty()
        {
            this.SS_University_Id = new HashSet<SS_University>();
            this.SS_Faculty_Id = new HashSet<SS_Faculty>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int Version { get; set; }
    
        public virtual ICollection<SS_University> SS_University_Id { get; set; }
        public virtual ICollection<SS_Faculty> SS_Faculty_Id { get; set; }
        public virtual SS_Player_Details SS_Player_Details_Id { get; set; }
    }
}
