//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupSpirit.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StartupSpiritDataContainer : DbContext
    {
        public StartupSpiritDataContainer()
            : base("name=StartupSpiritDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SS_Player> SS_PlayerSet { get; set; }
        public DbSet<SS_Player_Details> SS_Player_DetailsSet { get; set; }
        public DbSet<SS_University> SS_UniversitySet { get; set; }
        public DbSet<SS_Faculty> SS_FacultySet { get; set; }
        public DbSet<SS_Game_Component_Type> SS_Game_Component_TypeSet { get; set; }
        public DbSet<SS_University_Faculty> SS_University_FacultySet { get; set; }
        public DbSet<SS_Game_Component> SS_Game_ComponentSet { get; set; }
        public DbSet<SS_Game_Player_Progress> SS_Game_Player_ProgressSet { get; set; }
        public DbSet<SS_User_Role> SS_User_RoleSet { get; set; }
    }
}
